version: "3.3"
services:
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       environement:
        MYSQL_ROOT_PASSWORD: root
       volumes:
          - /home/mysql/data:/var/lib/mysql
      
      backend-container:
       image: atallahdoc/tpachat
       container_name: tpachatback
       restart: on-failure
       ports:
          - 8090:8090
       depends_on:
          - mysqldb
              